"""voucher file log table

Revision ID: 15d687a1f3f2
Revises: be271e924073
Create Date: 2021-11-10 11:19:16.701794

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "15d687a1f3f2"
down_revision = "4f5e04911e0a"
branch_labels = None
depends_on = None

fileagenttypes = sa.Enum("IMPORT", "UPDATE", name="fileagenttypes")


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "voucher_file_log",
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("file_name", sa.String(length=500), nullable=False),
        sa.Column("file_agent_type", fileagenttypes, nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("file_name", "file_agent_type", name="file_name_file_agent_type_unq"),
    )
    op.create_index(op.f("ix_voucher_file_log_file_agent_type"), "voucher_file_log", ["file_agent_type"], unique=False)
    op.create_index(op.f("ix_voucher_file_log_file_name"), "voucher_file_log", ["file_name"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_voucher_file_log_file_name"), table_name="voucher_file_log")
    op.drop_index(op.f("ix_voucher_file_log_file_agent_type"), table_name="voucher_file_log")
    op.drop_table("voucher_file_log")
    fileagenttypes.drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
