"""voucher table unique contraint

Revision ID: 32d186786bc0
Revises: cfb652f7f17b
Create Date: 2021-07-15 17:01:03.588831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "32d186786bc0"
down_revision = "cfb652f7f17b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "voucher_retailer",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("retailer_slug", sa.String(length=32), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_voucher_retailer_id"), "voucher_retailer", ["id"], unique=False)
    op.create_index(op.f("ix_voucher_retailer_retailer_slug"), "voucher_retailer", ["retailer_slug"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_voucher_retailer_retailer_slug"), table_name="voucher_retailer")
    op.drop_index(op.f("ix_voucher_retailer_id"), table_name="voucher_retailer")
    op.drop_table("voucher_retailer")
    # ### end Alembic commands ###
