"""alter unique constraint for vouchers

Revision ID: 9589c7115a36
Revises: 8f879d830ac9
Create Date: 2021-12-22 09:29:49.660234

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "9589c7115a36"
down_revision = "8f879d830ac9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("voucher_code_retailer_slug_unq", "voucher", type_="unique")
    op.create_unique_constraint(
        "voucher_code_retailer_slug_voucher_config_unq",
        "voucher",
        ["voucher_code", "retailer_slug", "voucher_config_id"],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("voucher_code_retailer_slug_voucher_config_unq", "voucher", type_="unique")
    op.create_unique_constraint("voucher_code_retailer_slug_unq", "voucher", ["voucher_code", "retailer_slug"])
    # ### end Alembic commands ###
