"""voucher import table

Revision ID: 9700bdae4ee7
Revises: 6395a5cbb0c8
Create Date: 2021-08-12 14:56:42.417371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9700bdae4ee7"
down_revision = "6395a5cbb0c8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "voucher_import",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column("voucher_code", sa.String(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("status", sa.Enum("ISSUED", "CANCELLED", "REDEEMED", name="voucherimportstatuses"), nullable=False),
        sa.Column("voucher_config_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["voucher_config_id"],
            ["voucher_config.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_voucher_import_id"), "voucher_import", ["id"], unique=False)
    op.create_index(op.f("ix_voucher_import_voucher_code"), "voucher_import", ["voucher_code"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_voucher_import_voucher_code"), table_name="voucher_import")
    op.drop_index(op.f("ix_voucher_import_id"), table_name="voucher_import")
    op.drop_table("voucher_import")
    # ### end Alembic commands ###
