"""retry tables constraints

Revision ID: adbed3358eaf
Revises: 2c286f5fe73a
Create Date: 2021-10-21 15:51:44.310839

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "adbed3358eaf"
down_revision = "2c286f5fe73a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_task_type_name", table_name="task_type")
    op.create_index(op.f("ix_task_type_name"), "task_type", ["name"], unique=True)
    op.create_unique_constraint("name_task_type_id_unq", "task_type_key", ["name", "task_type_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("name_task_type_id_unq", "task_type_key", type_="unique")
    op.drop_index(op.f("ix_task_type_name"), table_name="task_type")
    op.create_index("ix_task_type_name", "task_type", ["name"], unique=False)
    # ### end Alembic commands ###
