"""voucher and voucher_retailer tables

Revision ID: bccaaff2c733
Revises: 94cfb5b593f3
Create Date: 2021-07-16 17:03:59.721561

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "bccaaff2c733"
down_revision = "94cfb5b593f3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "voucher_retailer",
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("retailer_slug", sa.String(length=32), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_voucher_retailer_id"), "voucher_retailer", ["id"], unique=False)
    op.create_index(op.f("ix_voucher_retailer_retailer_slug"), "voucher_retailer", ["retailer_slug"], unique=True)
    op.create_table(
        "voucher",
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("voucher_code", sa.String(), nullable=False),
        sa.Column("allocated", sa.Boolean(), nullable=False),
        sa.Column("voucher_config_id", sa.Integer(), nullable=False),
        sa.Column("voucher_retailer_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["voucher_config_id"], ["voucher_config.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["voucher_retailer_id"],
            ["voucher_retailer.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("voucher_code", "voucher_retailer_id", name="voucher_code_voucher_retailer_unq"),
    )
    op.create_index(op.f("ix_voucher_id"), "voucher", ["id"], unique=False)
    op.create_index(op.f("ix_voucher_voucher_code"), "voucher", ["voucher_code"], unique=False)
    op.add_column("voucher_config", sa.Column("voucher_retailer_id", sa.Integer(), nullable=True))
    op.drop_index("ix_voucher_config_retailer_slug", table_name="voucher_config")
    op.drop_constraint("voucher_type_slug_retailer_slug_unq", "voucher_config", type_="unique")
    op.create_unique_constraint(
        "voucher_type_slug_voucher_retailer_unq", "voucher_config", ["voucher_type_slug", "voucher_retailer_id"]
    )
    op.create_foreign_key(
        "fk_voucher_config_voucher_retailer", "voucher_config", "voucher_retailer", ["voucher_retailer_id"], ["id"]
    )
    op.execute("INSERT INTO voucher_retailer (retailer_slug) SELECT distinct retailer_slug FROM voucher_config")
    op.execute(
        "UPDATE voucher_config SET voucher_retailer_id = voucher_retailer.id "
        "FROM voucher_retailer WHERE voucher_retailer.retailer_slug = voucher_config.retailer_slug"
    )
    op.drop_column("voucher_config", "retailer_slug")
    op.alter_column("voucher_config", "voucher_retailer_id", nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "voucher_config", sa.Column("retailer_slug", sa.VARCHAR(length=32), autoincrement=False, nullable=True)
    )
    op.execute(
        "UPDATE voucher_config SET retailer_slug = "
        "(SELECT retailer_slug FROM voucher_retailer where voucher_retailer.id = voucher_config.voucher_retailer_id) "
        "WHERE retailer_slug IS NULL"
    )
    op.alter_column("voucher_config", "retailer_slug", nullable=False)
    op.drop_constraint("fk_voucher_config_voucher_retailer", "voucher_config", type_="foreignkey")
    op.drop_constraint("voucher_type_slug_voucher_retailer_unq", "voucher_config", type_="unique")
    op.create_unique_constraint(
        "voucher_type_slug_retailer_slug_unq", "voucher_config", ["voucher_type_slug", "retailer_slug"]
    )
    op.create_index("ix_voucher_config_retailer_slug", "voucher_config", ["retailer_slug"], unique=False)
    op.drop_column("voucher_config", "voucher_retailer_id")
    op.drop_index(op.f("ix_voucher_voucher_code"), table_name="voucher")
    op.drop_index(op.f("ix_voucher_id"), table_name="voucher")
    op.drop_table("voucher")
    op.drop_index(op.f("ix_voucher_retailer_retailer_slug"), table_name="voucher_retailer")
    op.drop_index(op.f("ix_voucher_retailer_id"), table_name="voucher_retailer")
    op.drop_table("voucher_retailer")
    # ### end Alembic commands ###
