"""voucher update table

Revision ID: ef013ab3d4c0
Revises: 6395a5cbb0c8
Create Date: 2021-08-16 11:52:07.260224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ef013ab3d4c0"
down_revision = "6395a5cbb0c8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "voucher_update",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column("voucher_code", sa.String(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("status", sa.Enum("ISSUED", "CANCELLED", "REDEEMED", name="voucherupdatestatuses"), nullable=False),
        sa.Column("voucher_config_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["voucher_config_id"],
            ["voucher_config.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_voucher_update_id"), "voucher_update", ["id"], unique=False)
    op.create_index(op.f("ix_voucher_update_voucher_code"), "voucher_update", ["voucher_code"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_voucher_update_voucher_code"), table_name="voucher_update")
    op.drop_index(op.f("ix_voucher_update_id"), table_name="voucher_update")
    op.drop_table("voucher_update")
    # ### end Alembic commands ###
